### ISSUE TITLE
Error: unknown flag: --keystorePath

### ISSUE THREAD

**Issue by thebpmgroup** [outofcoffee/imposter#144]
Running in a Docker container

```
FROM outofcoffee/imposter-openapi
COPY config /opt/imposter/config/
COPY keystore /opt/imposter/keystore
ENTRYPOINT [ "imposter", "up" ]
CMD [ "/opt/imposter/config/", "--keystorePath", "/opt/imposter/keystore" ]
```

What gives? This is a legit flag according to the docs.

**Comment by outofcoffee** [comment]
Hi @thebpmgroup, the way Docker splits up the args means that it is treating the second and third element of the `CMD` array as unrelated. If, instead you had this:

```
FROM outofcoffee/imposter
COPY config /opt/imposter/config/
COPY keystore /opt/imposter/keystore
CMD [ "--configDir /opt/imposter/config/", "--keystorePath /opt/imposter/keystore" ]
```

...then I think it should pass in the values to the args correctly.

> Note the removal of the `ENTRYPOINT` and addition of `--configDir`.
