### ISSUE TITLE
http://localhost:8443/_spec show  blank page

### ISSUE THREAD

**Issue by damozhiying** [outofcoffee/imposter#15]
http://localhost:8443/_spec  will show  blank page, can't show swagger ui page ,what's the matter,  
i run   java -jar distro/build/libs/imposter.jar --plugin com.gatehill.imposter.plugin.openapi.OpenApiPluginImpl --configDir d:/config

**Comment by damozhiying** [comment]
SwaggerUIBundle
![qq 20171123204712](https://user-images.githubusercontent.com/10277950/33173565-97063926-d08f-11e7-8e9b-be0b1bd8769e.png)

**Comment by outofcoffee** [comment]
Hi @damozhiying please could you provide the console output from the browser?

**Comment by damozhiying** [comment]
@outofcoffee

**Comment by damozhiying** [comment]
@outofcoffee 
![Uploading QQ截图20171127100704.png…]()
![qq 20171127100841](https://user-images.githubusercontent.com/10277950/33247750-5ec35c46-d35b-11e7-8045-c35157472275.png)
![qq 20171127100902](https://user-images.githubusercontent.com/10277950/33247753-62609832-d35b-11e7-883b-347525a13e39.png)

**Comment by damozhiying** [comment]
@outofcoffee 
![qq 20171127100704](https://user-images.githubusercontent.com/10277950/33247769-71fe9654-d35b-11e7-82d4-15c24713bc84.png)

**Comment by outofcoffee** [comment]
Hi @damozhiying thanks very much for the information. It looks like a bug in the Swagger UI component, which is maintained separately here: https://github.com/swagger-api/swagger-ui

Would you be able to raise it as an issue with that project? It looks like some of the content of your Swagger file is not matching the required regular expression in Swagger UI.
