### ISSUE TITLE
http://localhost:8443/_spec show  blank page

### ISSUE THREAD

**Issue by damozhiying** [outofcoffee/imposter#16]
Accidentally shut down,please look here
https://github.com/outofcoffee/imposter/issues/15

**Comment by damozhiying** [comment]
@outofcoffee   please see here https://github.com/outofcoffee/imposter/issues/15,  thanks a lot

**Comment by damozhiying** [comment]
@outofcoffee  please

**Comment by damozhiying** [comment]
@outofcoffee  can you help me

**Comment by outofcoffee** [comment]
Hi, @damozhiying I've reopened #15 for you
