### ISSUE TITLE
openapi spec 3.*

### ISSUE THREAD

**Issue by dtunes** [outofcoffee/imposter#17]
Hi,

do you intent to support openapi spec 3.* in the near future?

**Comment by outofcoffee** [comment]
Hi @dtunes, we certainly do. Would you be in a position to help?

**Comment by dtunes** [comment]
I'd love to, but I haven't touched Java since the 90's.

**Comment by outofcoffee** [comment]
Work underway in branch: https://github.com/outofcoffee/imposter/tree/feature/openapi-v3?files=1

One of the main impediments at the moment is that the Java parser from the official OpenAPI project doesn't yet support examples when converting from V2 to V3. I'm using a workaround in the baby right now but it's not ideal.

**Comment by outofcoffee** [comment]
Here's the corresponding issue in the official parser project: https://github.com/swagger-api/swagger-parser/issues/540

**Comment by outofcoffee** [comment]
Beta support in Imposter is working, if not perfect. You can try it out using the Docker image `outofcoffee/imposter-openapi:oas3` tag.

**Comment by qsczsewsx** [comment]
hi pro,
Can you update the latest version of swagger-api / swagger-parser. I think this problem has been handled in the new version, and I need help from your project on docker

Thank you!

**Comment by outofcoffee** [comment]
Thanks, I'll have a look 👍

**Comment by outofcoffee** [comment]
PR raised: #32

**Comment by outofcoffee** [comment]
#32 merged at f91ad3
