### ISSUE TITLE
Only GET requests work with the Rest Plugin

### ISSUE THREAD

**Issue by martinhenderson2018** [outofcoffee/imposter#20]
Only GET requests seem to work with the Rest Plugin. Is it possible to extend it to include POST, PUT & DELETE ?

**Comment by paul-michalik** [comment]
Could anybody please confirm that this is true? I have now tried for some time to make a "POST" request  run through but with no success. Whenever the method is different from "GET"  I get a `404 Not Found` ersponse with the content:
```
<html><body><h1>Resource not found</h1></body></html>
```

**Comment by cyrixgr** [comment]
I have same issue as well.

**Comment by outofcoffee** [comment]
Hi folks, thanks for taking the time to raise this. To make sure I understand the use case, please could you explain what you're looking to achieve?

Is it CRUD behaviour where you're looking to POST to (arbitrary?) resources and subsequently GET/PUT/DELETE them? If so, #31 sounds similar. If not, is it something simpler where Imposter will return a canned status code (e.g. 201) when you POST to it, but not do anything with the payload?

**Comment by outofcoffee** [comment]
Hi @martinhenderson2018 @paul-michalik @cyrixgr as of v1.1.1 you now have the full range of HTTP methods available: https://github.com/outofcoffee/imposter/releases/tag/v1.1.1

In addition, you now also have control over the response headers using either static config or scripts, as well as the usual status code, content type, path params etc.
