### ISSUE TITLE
SFDC plugin - auth response has no Content-type header

### ISSUE THREAD

**Issue by pauturner** [outofcoffee/imposter#23]
**SFDC plugin**

**Test Step** - Send a HTTP POST request to sfdc auth endpoint.

**Expected Outcome** - Response should contain a Content-Type header

**Observe Outcome** - The http response from the auth endpoint has no content type header.  

I think it should have `Content-Type: application/json`

Will put in a PR

Example response from imposter service sfdc plugin is:

```
HTTP/1.1 200 OK
Content-Length: 74

{"access_token":"dummyAccessToken","instance_url":"http://localhost:8443"}
```

**Comment by outofcoffee** [comment]
Fixed by #26 and released in v0.7.0.
