### ISSUE TITLE
Any way to automatically mock preflight calls for OAS

### ISSUE THREAD

**Issue by anton-makarevich** [outofcoffee/imposter#246]
Hi, we are using imposter to run a mock server from our OAS file, works perfectly for API testing, but we don't have explicit definitions for OPTIONS in our specs, so it returns 405 when browser sends preflight requests. Is there any possibility to configure automatic responses in this case? I would expected something like mockCors: true in the config file, and then for every OPTIONS call to return 200 with a standard response allowing any origin/headers

**Comment by outofcoffee** [comment]
Hi @anton-makarevich - this is a great suggestion, thank you.

Do you have a view on how permissive the default mocked response should be? Even better, if you have a suggestion of the value of the respective CORS headers that would be a good starting point.

**Comment by outofcoffee** [comment]
Fixed by #366

**Comment by outofcoffee** [comment]
Released in [v3.16.0](https://github.com/outofcoffee/imposter/releases).

📖 [Documentation here](https://docs.imposter.sh/cors/)

@anton-makarevich the config you need here would be:

```yaml
cors:
  allowOrigins: all
```
