### ISSUE TITLE
Documenation issue, build creates "distro-0.6.0" not "imposter.jar" 

### ISSUE THREAD

**Issue by newgeekorder** [outofcoffee/imposter#25]
- Clone repo 
- Gradle build  
- the distro/build/ contains distro-0.6.0.jar not imposter.jar to as per the readme instructions

**Comment by outofcoffee** [comment]
Hi @newgeekorder thanks for raising this. 

Did you run the `shadowjar` or `build` task per 
https://github.com/outofcoffee/imposter/blob/master/docs/build.md?
