### ISSUE TITLE
Duplicate responses

### ISSUE THREAD

**Issue by LaurentiuTanase** [outofcoffee/imposter#34]
Hi!

I have a swagger.json file that responds with the same response:
The response for this get:
 "/comments": {
        "get": {
        "summary": "Get Comments",
        "description": "Get the comments based on data",
        "operationId": "getComments",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "headers": {},
            "schema": {
              "$ref": "#/definitions/CommentResponse"
            },
            "examples": {
              "application/json" : "{\n\"results\" : 1, \n\"items\" : [\n\t{\n\t\"id\" : 1,\n\t\"user\" : \"user\",\n\t\"creationTimestamp\" : \"2019-09-13T14:32:35.203Z\",\n\t\"content\" : \"This is a comment\"]}"
            }
          },

Is exactly as the one for the following:
"/comments/users": {
      "get": {
        "summary": "Get all users",
        "operationId": "getUsers",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "schema": {
              "$ref": "#/definitions/UsersResponse"
            },
            "examples": {
              "application/json" : "{\n\"results\" : 4, \n\"items\" : [\n\t{\n\t\t \"name\" : \"user1\" \n\t},\n\t{ \n\t\t \"name\" : \"user2\" \n\t}, \n\t{ \n\t\t \"name\" : \"user3\" \n\t}, \n\t{ \n\t\t\"name\" : \"user4\" \n\t}"
            }
          },

I didn't used any groovy scripts or something else. Only one -config file to get the swagger.json file and one docker-compose to run the docker image.

Any ideas why this is happenning?

**Comment by outofcoffee** [comment]
Hi @LaurentiuTanase please could you share the Swagger file and config file here?

**Comment by outofcoffee** [comment]
Hi @LaurentiuTanase I'm closing this for now, but please feel free to provide more information if/when you can.
