### ISSUE TITLE
simple-salesforce support

### ISSUE THREAD

**Issue by comtihon** [outofcoffee/imposter#35]
Hi,
is it possible to run sfdc with simple_salesforce as a client?
I run the mock:
```
docker run -ti -p 8080:8080   
                      -p 443:443  
                      -v $(pwd)/config:/opt/imposter/config 
                      -v $(pwd)/keystore:/opt/imposter/keystore    
                      outofcoffee/imposter-sfdc -c /opt/imposter/config 
                                                               --tlsEnabled 
                                                               --listenPort 443
                                                               --serverUrl http://localhost:443 
                                                               --keystorePath /opt/imposter/keystore/ssl.jks
                                                               --keystorePassword password
```
Then I just use:
```
from simple_salesforce import Salesforce
sf = Salesforce(instance_url='https://127.0.0.1', session_id='')
sf.Contact.create({'LastName':'Smith','Email':'example@example.com'})
```
And get error:
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=443): Max retries exceeded with url: /services/data/v38.0/sobjects/Contact/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```
If you know a way to make simple-salesforce work without ssl, it will also help me.
Thanks.

**Comment by outofcoffee** [comment]
Hi @comtihon please check out the docs for the Salesforce plugin: https://github.com/outofcoffee/imposter/blob/master/docs/sfdc_plugin.md in particular the SSL/TLS section

**Comment by comtihon** [comment]
Hi @outofcoffee that's exactly what I did.
Salesforce plugin page is not so informative unfortunately. It just points to [TLS](https://github.com/outofcoffee/imposter/blob/master/docs/tls_ssl.md) page. And TLS page says I need to use an ssl key, what I already did.
And the error is - simple salesforce can't verify it (I used your key from the repository)

**Comment by outofcoffee** [comment]
Hi @comtihon, SSL certificates must match the domain where you’re hosting an application, e.g. https://example.com would need a certificate issued for the example.com domain. Normally, you would obtain a signed certificate for a given domain via a third party provider. Certificates signed by a public certificate authority will generally be trusted by client applications such as the library you’re using. If you generate a certificate yourself, or use the test one in this project, they are known as self-signed certificates. Self-signed certificates are untrusted and you usually have to configure your client to accept them explicitly, such as via a trust store or other JVM-wise SSL configuration. HTH :)
