### ISSUE TITLE
Letter case of predefined specification properties

### ISSUE THREAD

**Issue by jeanloop** [outofcoffee/imposter#37]
Hi,

first I would like to say thanks for this awesome software. I've been using it for a few OAS projects now and it's really great and useful.

I've noticed a little problem a couple of times though. When using Swagger UI, some things do not work. I've done some research and the problem seems to be, that some property values are transformed to uppercase when imposter produces the combined.json.

For example, when _securitySchemes_ are defined in the spec with _type: http_, in combined.json it reads _type: HTTP_. Swagger UI doesn't like this, apparently, and so the authentication popup is blank when it opens. From the OpenAPI documentation it looks like the value should be lowercase.

The same happens with the style property of operation parameters.

I'm building my own docker container based on _outofcoffee/imposter-openapi_.

Can you give me a hint on how to fix this?

Thanks!
Jan

**Comment by outofcoffee** [comment]
Hi @jeanloop, thanks very much for getting in touch!

Do you have an example before/after JSON you could share that reproduces the issue?

Also, please could you let me know the version of swagger UI you’re using; is it the embedded one? If so, this was updated in the latest beta, so would be keen to see if it’s still an issue.

**Comment by jeanloop** [comment]
Hi @outofcoffee,

sorry for the delay, I didn't find the time to setup a simple test case until today.

So here it is:

Simply unzip the attached file into a folder, cd into it on the command line and run:
docker run --rm -ti -p 8080:8080 -v $(pwd)/:/opt/imposter/config outofcoffee/imposter-openapi

I used the OAS3 spec from the examples here: https://raw.githubusercontent.com/outofcoffee/imposter/master/plugin/openapi/src/test/resources/config/openapi3-with-examples.yaml

The only change: I added a securityScheme definition for a bearer token and configured security for all endpoints.

When you run it and look at the swagger UI, click on the "authenticate" button above the list of endpoints. The window will open but does not show any content. It should show an interface to login by providing a token.

When you look at the combined.json produced by the server, you may notice, that the components/securitySchemes definition is now included, but the letter case of the type-property has changed from lowercase to uppercase. Swagger UI does not like that. I tested it by filtering combined.json using a regular expression before it is sent by the server. When using lowercase values, all is fine.

The same problem occurs when defining parameters using the style-property. There may be other properties with the same issue that I did not use yet.

Since the OAS documentation defines those values as lowercase, I think that swagger UI is behaving correctly. See here for example: https://swagger.io/docs/specification/authentication/bearer-authentication/

I debugged the imposter java code a bit trying to find the source of the problem and I think it may be related to this file: https://github.com/outofcoffee/imposter/blob/master/core/src/main/groovy/com/gatehill/imposter/util/MapUtil.java.

Hope this helps identifying the problem.

Thanks again for this great tool!

[impostertest.zip](https://github.com/outofcoffee/imposter/files/4133483/impostertest.zip)

**Comment by outofcoffee** [comment]
Thank you for the really comprehensive bug report and description. This helped immensely in tracking down this bug. It is finally fixed in 492893224c8b34d67b82319e1ec601d3b50c1a9b, released in v2.2.0.
