### ISSUE TITLE
imposter (api mock) docker cors problem

### ISSUE THREAD

**Issue by carmelolg** [outofcoffee/imposter#38]
Hi,

I have a question about https://github.com/outofcoffee/imposter
I dockerize this mock server for development purpose but from my web application in Angular (that call the rest services mocked) I have the cors policy issue.
How can I do? I need a gateway between webapp and our mocks on server-side? 

Thanks in advance.

**Comment by outofcoffee** [comment]
Hi @carmelolg, if you’re looking to expose your APIs on the same host as your web app, one way to achieve what you’re looking for would be to put a reverse proxy server in front and route based on the path.

A good option would be nginx, using the `proxy_pass` directive in your nginx configuration inside a `location` block.

**Comment by carmelolg** [comment]
> Hi @carmelolg, if you’re looking to expose your APIs on the same host as your web app, one way to achieve what you’re looking for would be to put a reverse proxy server in front and route based on the path.
> 
> A good option might be nginx, using the `proxy_pass` directive in your nginx configuration inside one or more `location` blocks.

It's exactly what I did 😃 It's the only solution that I designed since CORS policy are not supported in these solution.
Thanks
