### ISSUE TITLE
How to disable auto-update

### ISSUE THREAD

**Issue by hilsonp** [outofcoffee/imposter#393]
Hello,

To use imposter in a CI/CD pipeline, we should control which version of imposter runs.

We may look into using the maven repo but I think in order to have the automatic reload we should not use the jar but rather the imposter executable. Am I correct ?

When launching the imposter executable, the first thing it does is auto-updating.
Is there a way to turn this off in the configuration file ?

Thank you.

**Comment by outofcoffee** [comment]
Hi @hilsonp, thanks for opening this issue.

You can pin the version of Imposter so you always get the same engine version.

You can do this in a few ways using the CLI:

1. Pass the `--version x.y.z` argument to `imposter up`, or
2. Set `version: x.y.z` in an `.imposter.yaml` file in the config directory, or
3. Set `version: x.y.z` in your `$HOME/imposter/config.yaml` file

I hope this is helpful!
