### ISSUE TITLE
Groovy scripts working dir

### ISSUE THREAD

**Issue by hilsonp** [outofcoffee/imposter#394]
Hello,

When one use a groovy code, it is in the scope of one particular mock, right ?

As of now, if a groovy code writes a file, it is relative to "from where the imposter was launched".
It would be cleaner to have the groovy working dir set to where the "parent" mock configuration is stored.

Eg:

- The /home/imposter/mocks directory contains
  - mock1/mock1-config.yaml
  - mock1/mock1.groovy
  - mock2/mock2-config.yaml
  - mock2/mock2.groovy
- I'm launching the 'imposter up -r' from /home/imposter/mocks
- Creating a file "./mock1.txt" from mock1.groovy launched by mock1 mock should ideally create a file relative to /home/imposter/mocks/mock1 (eg: /home/imposter/mocks/mock1/mock1.txt)
- Creating a file "./mock2.txt" from mock2.groovy launched by mock2 mock should ideally create a file relative to /home/imposter/mocks/mock2 (eg: /home/imposter/mocks/mock2/mock2.txt)

This allows to create mocks without knowing where, in which directory structure, and from where the imposter is launched.
This decouples the mock creation and runtime.

Our work-around would be to run one imposter per mock and set the working dir of each imposter to be the path to the mock config file.

Did I miss something ?

Best regards,

**Comment by outofcoffee** [comment]
Hi @hilsonp, thanks for raising this.

You can access the path of the directory containing the config file for the script using the `config.dir` property.

For example:

```groovy
logger.info("Path to config dir: " + config.dir)
```

Hopefully you can use this to construct the full path you need, e.g.

```groovy
def someFile = new java.io.File(config.dir, "mock1.txt")
// write to someFile
```
