### ISSUE TITLE
Is there a mechanism to test error codes?

### ISSUE THREAD

**Issue by haani-niyaz** [outofcoffee/imposter#41]
I use OpenAPI. I have multiple responses for each path, including error responses like `404`, `409` etc.

Is there a way to trigger an API call to to test error codes?

Example:

```
    /rest/api/2/project/{projectIdOrKey}:
      get:
        tags:
          - jira
        summary: get project
        operationId: getProject
        description: Gets information about a project
        parameters:
          - in: path
            name: projectIdOrKey
            schema:
              type: string
            required: true
            example: TEST
            description: Numeric ID or key of the project
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Project'
          '404':
            description: The project is not found, or the calling user does not have permission to view it.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'         
```

**Comment by outofcoffee** [comment]
Hi @haani-niyaz, thanks for your question. Yes, Imposter allows you to control the response behaviour via scripting.

This enables you to determine which status code (and thus corresponding example) to return. You can examine various properties of the request (headers, parameters etc.) to determine if you want to return an error code or a success status code.

Here's some information about scripting responses: https://github.com/outofcoffee/imposter/blob/master/docs/scripting.md
