### ISSUE TITLE
Imposter to return a response from examples as a round-robin

### ISSUE THREAD

**Issue by sjabiulla** [outofcoffee/imposter#42]
Currently, from the open api spec, when I start imposter , I'm able to start server and access my endpoint via API. When I invoke API, I'm able to get the response which I have configured as example in open api spec. If I configure, multiple examples, it's always returning the last example mentioned in openapi spec. Is there an option that we can configure to pick the reponse like a round robin behavior on the examples available rather than picking the last example all the time

**Comment by outofcoffee** [comment]
Hi @sjabiulla, thanks for your question. Imposter allows you to control the response behaviour via scripting, but this is limited to:

1. the script determining which status code (and thus corresponding example) to return
2. the script returning a literal string response

With option 2 you do have a way to do this, but it wouldn't necessarily mirror the content in the spec file - it would be whatever you configured in the script.

Here's some information about scripting responses: https://github.com/outofcoffee/imposter/blob/master/docs/scripting.md

**Comment by sjabiulla** [comment]
Thanks for the detailed information. 

But, can I script responses with openapi plugin?  

I see that, in the example that's mentioned here https://github.com/outofcoffee/imposter/blob/master/docs/scripting.md is using REST plugin.

**Comment by outofcoffee** [comment]
All current plugins support scripting.

If you were to take the example from above and change the plugin to `openapi`, and remove the `path` portion you don't need, it would look like this:

```yaml
# scripted-openapi-config.yaml
---
plugin: openapi
response:
  scriptFile: example.groovy
```

This way your `example.groovy` can control the responses, including specifying:

1. a specific example name to return
2. the content of a file to return
3. a literal string to return

**Comment by outofcoffee** [comment]
Documentation updated: https://github.com/outofcoffee/imposter/blob/master/docs/openapi_plugin.md
