### ISSUE TITLE
Browse history of REST requests sent to Imposter

### ISSUE THREAD

**Issue by daniel-lam-vl** [outofcoffee/imposter#44]
Is it possible browse the REST requests that have been made to/from Imposter? (via an endpoint)

**Comment by kierans** [comment]
This is something that would be very useful when paired with the OpenAPI plugin so that the imposter can return example responses, and the tests can assert what was sent to the imposter (especially when using client created with the Open API client generator)

**Comment by outofcoffee** [comment]
This is a great feature idea 💡 

I'd be happy to accept a pull request for this. Would either of you be in a position to contribute this?
