### ISSUE TITLE
Replace deprecated Nashorn scripting implementation

### ISSUE THREAD

**Issue by outofcoffee** [outofcoffee/imposter#46]
Nashorn, the provider of JavaScript scripting support is deprecated as of Java 11.

The GraalVM implementation is intended to eventually replace the Nashorn implementation.

**Comment by outofcoffee** [comment]
Module added in 028875657848a71a16fd25caf05cf26f6e04a9a2.

**Comment by pcornish** [comment]
As of v1.3.0, the GraalVM implementation is now merged, but Nashorn is still the default.

**Comment by outofcoffee** [comment]
As of v1.3.0, the GraalVM implementation is now merged, but Nashorn is still the default.

**Comment by pcornish** [comment]
Currently Graal.js doesn't have special Map or List accessor syntax: https://github.com/oracle/graaljs/issues/107

This makes accessing things like params more cumbersome:

Nashorn:
```javascript
request.headers.Authorization
request.params.foo
```

Graal.js
```javascript
request.headers.get('Authorization')
request.params.get('foo')
```

**Comment by outofcoffee** [comment]
Graal.js now supports [map-like data structures](https://github.com/oracle/graaljs/issues/143) as of [v21.1.0](https://www.graalvm.org/release-notes/21_1/)

> Added support for map-like data structures (issue #143) ... Java host interoperability was improved to handle java.util.Map implementations to make them look like guest language hash maps. This feature can be enabled and disabled with HostAccess.Builder.allowMapAccess(boolean).

**Comment by outofcoffee** [comment]
As of 3.40.0, the `js-graal` plugin is pretty mature. We should look at swapping the default to Graal in the next major version and move `js-nashorn` to an external plugin.

**Comment by outofcoffee** [comment]
Done in [v4.0.0](https://github.com/outofcoffee/imposter/releases/tag/v4.0.0).

Graal is now the default JavaScript plugin. Nashorn is available as a standalone plugin for legacy compatibility.
