### ISSUE TITLE
Can I add basepath for _spec endpoint?

### ISSUE THREAD

**Issue by francardoso93** [outofcoffee/imposter#469]
Instead of accessing OpenAPI through
https://mycustomdomain.com/_spec

I'd like to be able to access it through
https://mycustomdomain.com/api/core-mock/v1/_spec (Basepath: `api/core-mock/v1/`) to match my infrastructure routing patterns.

Is it possible?

**Comment by outofcoffee** [comment]
Hi @francardoso93 (cc: @sameer-coder), from v3.32.0 you can set the environment variable `IMPOSTER_OPENAPI_SPEC_PATH_PREFIX`, to override the default `/_spec` prefix.

For example:

```
IMPOSTER_OPENAPI_SPEC_PATH_PREFIX="/api/core-mock/v1/_spec"
```

...will make the spec UI accessible at http://localhost:8080/api/core-mock/v1/_spec/

**Comment by outofcoffee** [comment]
Added example to docs in 38176774.
