### ISSUE TITLE
Run docker command using NPM script

### ISSUE THREAD

**Issue by hamzanaveedmalik** [outofcoffee/imposter#48]
How do we run the Docker command to start the Mock Server in the NPM script.

**Comment by outofcoffee** [comment]
Hi @hamzanaveedmalik, do you have a sample project you can share, to help explain what you’re trying to do?

**Comment by outofcoffee** [comment]
Hi @hamzanaveedmalik, hopefully this project covers what you are trying to do: https://github.com/gatehill/imposter-js
