### ISSUE TITLE
Version of the swagger UI (seems to need updating)

### ISSUE THREAD

**Issue by cableman** [outofcoffee/imposter#52]
Hey

I have been trying mock a OpenAPI version 3.0 and run into issues where the http://localhost:8080/_spec do not send path parameters with the request to the server.

It generates this url `http://localhost/v1/screen/,` which should have been `http://localhost/v1/screen/497f6eca-6276-1596-bfeb-53ceb43a6f54`. The OpenAPI definition works perfectly in https://editor.swagger.io/.

I can see that the swagger UI files in https://github.com/outofcoffee/imposter/tree/master/plugin/openapi/src/main/html have not be updated and the current release is v3.49.0 where the one in imposter is v3.24.3.

![Screenshot 2021-06-01 at 22 38 37](https://user-images.githubusercontent.com/111397/120387393-24e59300-c32a-11eb-8d24-f84a429099ee.png)

Would it be possible to update the swagger UI version to fix this issue

**Comment by outofcoffee** [comment]
Hi @cableman - yes, an update should be no problem.

**Comment by outofcoffee** [comment]
Updated to Swagger UI 3.50.0 in 2a8d08b77bde46293a6de1e39ece9ceb5f6b548f.

Available in Docker hub under the `:beta` tag, e.g. `outofcoffee/imposter-openapi:beta`

**Comment by cableman** [comment]
Great :-)

**Comment by outofcoffee** [comment]
Thanks for your help :)
