### ISSUE TITLE
Upgrade base image to newer version to resolve vunerabilities

### ISSUE THREAD

**Issue by nickperkins** [outofcoffee/imposter#539]
The [current base image](https://github.com/outofcoffee/imposter/blob/86ff84c1385edf5e5de3cf8ff91e26bea45c9963/distro/base/Dockerfile#L1) uses ubuntu focal 20.04. This image contains a number of vulnerabilities due to its age.

It would be great to see this updated to a newer version, such as [eclipse-temurin:11.0.22_7-jre-jammy](https://hub.docker.com/layers/library/eclipse-temurin/11.0.22_7-jre-jammy/images/sha256-e3d185355a1c524a0c5922ed56dd07b9d9f7e9617178a5997d52686c67335c70?context=explore)

**Comment by outofcoffee** [comment]
This might be the Dependabot issue (though closed, latest comment suggests not resolved): https://github.com/dependabot/dependabot-core/issues/3929

**Comment by outofcoffee** [comment]
Released in [v3.35.2](https://github.com/outofcoffee/imposter/releases).
