### ISSUE TITLE
No API path found that matches request

### ISSUE THREAD

**Issue by suityou01** [outofcoffee/imposter#56]
I believe I am passing a valid request for the specification

```
swagger: "2.0"
info:
  version: "2021-11-03T14:58:25Z"
  title: "charges-dev"
host: "localhost:8080"
basePath: "/charges"
schemes:
- "https"
- "http"
  paths:
    /myendoint:
      post:
        tags:
        - "tags"
        summary: "Post endpoint"
        description: "takes a payload
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
        - in: "body"
          name: "PostBody"
          description: "Post Body"
          required: true
          schema:
            $ref: "#/definitions/PostBodyDef
```

`curl --location --request POST 'localhost:8080/charges/myendpoint/' \
--header 'Content-Type: application/json' \
--data-raw ' [
    { ....`

Paths match
Verbs match
Payload matches

Config

`plugin: openapi
specFile: output.yml
validation:
  request: true
  levels:
    validation.request.body.missing: WARN
    validation.request.body.unexpected: WARN
    validation.request.path.missing: ERROR`

What else do I need to match?

**Comment by outofcoffee** [comment]
HI @suityou01, would you be able to provide a full spec file?

This might be an issue with the formatting in the GitHub issue, but the extract above has some issues that prevent easy reproduction of the issue. For example, it doesn't appear to have `paths` defined at the correct level of the document, it refers to a schema definition that's not present and the `description` key is missing a closing double quote.

If you are able to provide a full spec file; I'm happy to help take a look.

**Comment by outofcoffee** [comment]
@suityou01 I think I may have spotted a typo - in the spec you have:

```
paths:
    /myendoint:
      post:
```

note: `myendoint` - but your curl command uses `localhost:8080/charges/myendpoint/` - note `myendpoint`
