### ISSUE TITLE
Trivy reports lots of vulnerabilities

### ISSUE THREAD

**Issue by gregtyler** [outofcoffee/imposter#579]
We just added Imposter to a repo that automatically uses [Trivy](https://trivy.dev/) to scan all repos, and it brought up 54 vulnerable packages.

```sh
trivy image outofcoffee/imposter
```

[Trivy CLI output](https://github.com/user-attachments/files/15510883/imposter-trivy-output.txt)

Some of those seem to be from the Ubuntu base image you're using, but I was particularly surprised to see so many golang issues, since AFAIK Imposter is written in Java.

These may all be false positives, but I thought I should bring it to your attention.

**Comment by outofcoffee** [comment]
Hi @gregtyler, thank you for the report.

The base image has been bumped to the latest JDK 11 version for the main `outofcoffee/imposter` image. There are fewer vulnerabilities in this version.

In addition, there's also a `distroless` image, which has far fewer dependencies:
https://hub.docker.com/r/outofcoffee/imposter-distroless/tags

**Comment by gregtyler** [comment]
Thanks for the update, and the pointer to the distroless version
