### ISSUE TITLE
ARM64 Support?

### ISSUE THREAD

**Issue by bnjmn** [outofcoffee/imposter#60]
Hello! Thank you for this project!

Any plans to publish a docker image with arm64 support? This would be very helpful for those running the project on arm based machines like the M1 mac chips. Thanks again!

**Comment by outofcoffee** [comment]
Hi @bnjmn - yes, it would be good to support arm64. We use GitHub Actions for building the images, so it looks like we'd need a combination of:

- arm64 GitHub Actions runner
- buildx support to produce multi-architecture Docker images or come up with a naming scheme for Docker image tags to distinguish the arm64 ones

Thoughts welcome!

**Comment by outofcoffee** [comment]
Steps involved:

Switching from `docker_build.sh` to using GitHub Actions for image build/push. Specifically:
- https://github.com/docker/setup-qemu-action
- https://github.com/docker/setup-buildx-action
- https://github.com/marketplace/actions/build-and-push-docker-images

Using a multiplatform base image, such as [eclipse-temurin/8u322-b06-jre-focal](https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/8u322-b06-jre-focal/images/sha256-001d11f71f928f4954572c1068041a1eb4df1a21cc3118559c91959dec4d47e5?context=explore)

**Comment by outofcoffee** [comment]
Spike underway in branch [spike/multi-arch](https://github.com/outofcoffee/imposter/tree/spike/multi-arch).

Currently supports arm64 and amd64.
