### ISSUE TITLE
Support multiple OpenAPI specifications

### ISSUE THREAD

**Issue by CrAzE124** [outofcoffee/imposter#622]
Hi there, 

I'm busy experimenting with imposter to set up a mock server for external users. If I understand [the docs](https://docs.imposter.sh/configuration/#multiple-resources-example) correctly, it should be possible to provide multiple API specifications to mock out, but I am unsure how to go about this. 

Is this possible at all? If so, could we perhaps update the documentation to make it more clear how exactly to configure things?

**Comment by outofcoffee** [comment]
Hi @CrAzE124, thanks for raising this. Imposter lets you provide one or more config files. These will reside in the configuration directory you specify. To have multiple OpenAPI specs, provide a configuration file for each, e.g.

```
/path/to/config/dir
spec1.yaml
spec1-config.yaml
spec2.yaml
spec2-config.yaml
```

Within a config file, it can be as simple as:

```yaml
plugin: openapi
specFile: spec1.yaml
```

**Comment by outofcoffee** [comment]
Here’s some additional information in case this is useful:
https://docs.imposter.sh/config_discovery/

**Comment by CrAzE124** [comment]
Perfect, thanks for the quick help, much appreciated!
