### ISSUE TITLE
Proxy: allow option to record request body as part of output config

### ISSUE THREAD

**Issue by nickperkins** [outofcoffee/imposter#628]
We're trying to use imposter to record responses for some POST requests. The responses change depending on the body data being sent, but imposter doesn't record that information in the config of the recording.

It would be helpful if imposter could store the request body when writing out the config so that you can then have body matching for the requests.

**Comment by outofcoffee** [comment]
Hi @nickperkins, thank you for raising this. This is a great idea!

Would you be in a position to submit a pull request to the [imposter-cli](https://github.com/gatehill/imposter-cli) project?

**Comment by outofcoffee** [comment]
Added support in the engine for matching on arbitrary request bodies (not just JSON and XML) in [v4.1.0](https://github.com/outofcoffee/imposter/releases/tag/v4.1.0), which is a useful step towards this.

Next step would be to capture request bodies in the CLI and use the new raw request body matcher in the config it writes.

**Comment by outofcoffee** [comment]
Hi @nickperkins, this is now supported from CLI version [v0.45.0](https://github.com/gatehill/imposter-cli/releases).
