### ISSUE TITLE
SOAP content configuration ignored when status code is 500

### ISSUE THREAD

**Issue by outofcoffee** [outofcoffee/imposter#658]
@driesva [wrote](https://github.com/outofcoffee/imposter/pull/650#issuecomment-2454985901):
> @outofcoffee we discovered an issue with our config due to this feature.
> 
> We do not have SOAP-Fault declarations in our WSDL and we had the following in our config:
> 
> ```
>     response:
>       statusCode: 500
>       content: |
>         <soapenv:Envelope
>             xmlns:soapenv = "http://schemas.xmlsoap.org/soap/envelope/"
>             xmlns:xsi = "http://www.w3.org/1999/XMLSchema-instance"
>             xmlns:xsd = "http://www.w3.org/1999/XMLSchema">
>           <soapenv:Body>
>             <soapenv:Fault>
>               <faultcode>soapenv:Server</faultcode>
>               <faultstring>A SOAP fault</faultstring>
>             </soapenv:Fault>
>           </soapenv:Body>
>         </soapenv:Envelope>
> ```
> 
> The content is not served anymore and we see the following warning: `WARN i.g.i.p.s.SoapPluginImpl - No output or fault definition found in WSDL for POST`
> 
> I doubt if the SOAP / WSDL spec mandates that a (standard) fault must be declared in the WSDL.

**Comment by outofcoffee** [comment]
Fix in beta: 4fa3797df79dbfb61455a1939d9e65fa9fa3b594

**Comment by outofcoffee** [comment]
Fixed in [v4.2.1](https://github.com/outofcoffee/imposter/releases).

**Comment by outofcoffee** [comment]
FYI @driesva

**Comment by driesva** [comment]
@outofcoffee I've tested [v4.2.1](https://github.com/outofcoffee/imposter/releases) and it works!

Thanks

**Comment by outofcoffee** [comment]
Thank you for confirming @driesva!
