### ISSUE TITLE
Problems with embed in Java unit tests

### ISSUE THREAD

**Issue by mcasas993** [outofcoffee/imposter#660]
I'm trying to do a simple unit test through this [guide](https://docs.imposter.sh/embed_jvm/), but I can't import OpenApiMockEngine and ImposterBuilder.

This is my build.gradle:

```
def versions = [
    // Test libraries
    mockito: "5.12.0",
    junit: "4.13.2",
    // Jackson is used to manage JSON objects (serialization / deserialization)
    jackson: "2.17.2",
    jackson_databind: "2.17.2",
    // Used to mock the Wazuh Server API
    imposter: "4.1.2"
]

dependencies {
    testImplementation "org.mockito:mockito-core:${versions.mockito}"
    testImplementation "junit:junit:${versions.junit}"
        // imposter
    testImplementation "io.gatehill.imposter:distro-embedded:${versions.imposter}"
    testImplementation "io.gatehill.imposter:core:imposter-engine:${versions.imposter}"
    testImplementation "io.gatehill.imposter:imposter-server:${versions.imposter}"
    testImplementation "io.gatehill.imposter:config-dynamic:${versions.imposter}"
    testImplementation "io.gatehill.imposter:mock-openapi:${versions.imposter}"
}

repositories {
    mavenLocal()
    maven { url "https://aws.oss.sonatype.org/content/repositories/snapshots" }
    mavenCentral()
    maven { url "https://plugins.gradle.org/m2/" }
    // imposter maven repository
    maven { url "https://s3-eu-west-1.amazonaws.com/gatehillsoftware-maven/releases/" }
}
```
I can see the OpenApiMockEngine and ImposterBuilder class in the Imposter code on github, but when I tried to import them, I couldn't find them. 

I checked this [example](https://github.com/outofcoffee/imposter/blob/main/examples/junit-sample/src/test/java/io/gatehill/imposter/sample/PetServiceTest.java) and tried to replicate it. Not only I can't find those classes, I can't even find openapi inside io.gatehill.imposter. 

![image](https://github.com/user-attachments/assets/90496d5d-9f03-4051-9eb3-c86884766df7)

**Comment by outofcoffee** [comment]
Hi @mcasas993, thank you for raising this.

There was an issue with the transitive dependencies for one of the Maven artifacts, which has been fixed in [v4.2.2](https://github.com/outofcoffee/imposter/releases).
