### ISSUE TITLE
Should provide a withScript(String) function

### ISSUE THREAD

**Issue by cscetbon** [outofcoffee/imposter#68]
It seems impossible to load a script using `withFile(filename).template()`. In order to have different scripts doing different actions but share common code (like decoding parameters, storing in stores etc..) a function **withScript(String)** would be useful. Of course the request store should be available through all those scripts for the whole life cycle of the current HTTP request like it is today even if multiple scripts are called.

For instance I'd like to do something like
```
# mock-config.yaml
plugin: rest

resources:
  - path: /my/path
    method: POST
    response:
      scriptFile: dispatcher.groovy
```

```
// dispatcher.groovy
def requestStore = stores.open('request')
def queryParams = context.request.body.split('&').collectEntries {
    param -> param.split('=').collect { URLDecoder.decode(it) }
}

// store all important params in request store
...

// do some other stuff like storing calculating values in request store 
...
// check if queryParams.wsfunction is known and call the corresponding script
if (....){
      respond()
          .withScript("${queryParams.wsfunction}.groovy")
else{
      respond()
          .withStatusCode(400)
          .skipDefaultBehaviour()
}
```

**Comment by outofcoffee** [comment]
If you are looking for more complex script behaviour, allowing for separation of logic across different files etc. consider having a look at https://github.com/gatehill/imposter-js/, which has examples for both TypeScript and modern ES/JavaScript.

Granted, it does not cover the Groovy use case, but if you would be interested in doing something like that project for Groovy, I would be happy to work with you on this.

**Comment by cscetbon** [comment]
It seems to me that in those examples what is done is bundling things together at build time in order for it to be accessible. Any reason why the current folder is not accessible just to load anything that is under the current folder ? It seems also that you would prefer to be able to import code than having WithScript() function like I propose which seems more consistent with your configuration file.

**Comment by outofcoffee** [comment]
@cscetbon I've added a `loadDynamic('somescript.groovy')` method to the Groovy DSL in v2.11.0. This handles the path resolution for Groovy script files, relative to the main script referenced from config.

You can see a unit test of this functionality at:
[scripting/groovy/src/test/java/io/gatehill/imposter/service/GroovyScriptIncludeFileTest.kt](https://github.com/outofcoffee/imposter/blob/main/scripting/groovy/src/test/java/io/gatehill/imposter/service/GroovyScriptIncludeFileTest.kt)

and the referenced files (`entrypoint.groovy` and `included.groovy`) under:
[scripting/groovy/src/test/resources/script/](https://github.com/outofcoffee/imposter/blob/main/scripting/groovy/src/test/resources/script/)

**Comment by cscetbon** [comment]
Nice, let me know when there is a docker image I can use to try it.

**Comment by cscetbon** [comment]
@outofcoffee any idea why I can't do something like 👇 
```
# mock-config.yaml
plugin: rest

resources:
  - path: /my/path
    method: POST
    response:
      scriptFile: dispatcher.groovy
```

```
// dispatcher.groovy
return loadDynamic('other.groovy')
```

```
// other.groovy
return respond()
            .withStatusCode(404)
            .skipDefaultBehaviour()
```

I get the following which doesn't make much sense

```
*   Trying ::1:8888...
* Connected to localhost (::1) port 8888 (#0)
> POST /my/path HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Imposter-Request: 295bb094-9bb0-47b2-bc0f-40ba72d45c4b
< Server: imposter
< content-length: 0
<
* Connection #0 to host localhost left intact
```

**Comment by pcornish** [comment]
Hi @cscetbon, the result of calling the `loadDynamic(..)` method is a new Groovy script object. Specifically, the `GroovyClassLoader` returns a subclass of [groovy.lang.Script](https://docs.groovy-lang.org/latest/html/api/groovy/lang/Script.html).

This object does not share global state ('bindings') with the calling script, so it doesn't have access to DSL functions like `respond()` etc.

For now, a work-around would be to use the dynamically-loaded scripts to do computation/logic and return an object for your dispatcher to then use when it calls `respond()`...

---

The reason for the 200 response in the case above is that calling `return` on the result of `loadDynamic` is just causing the script engine to terminate with a useless object, without executing the script inside it.

You could try doing something like this instead:

```groovy
// dispatcher.groovy
def other = loadDynamic('other.groovy')
return other()
```

(☝️ this is a guess - I haven't run this myself though)

**Comment by outofcoffee** [comment]
Hi @cscetbon, the result of calling the `loadDynamic(..)` method is a new Groovy script object. Specifically, the `GroovyClassLoader` returns a subclass of [groovy.lang.Script](https://docs.groovy-lang.org/latest/html/api/groovy/lang/Script.html).

This object does not share global state ('bindings') with the calling script, so it doesn't have access to DSL functions like `respond()` etc.

For now, a work-around would be to use the dynamically-loaded scripts to do computation/logic and return an object for your dispatcher to then use when it calls `respond()`...

---

The reason for the 200 response in the case above is that calling `return` on the result of `loadDynamic` is just causing the script engine to terminate with a useless object, without executing the script inside it.

You could try doing something like this instead:

```groovy
// dispatcher.groovy
def other = loadDynamic('other.groovy')
return other()
```

(☝️ this is a guess - I haven't run this myself though)

**Comment by cscetbon** [comment]
Yeah it's a bit annoying but I see. I was expecting something closer to what is done in the configuration but I see. Thanks

**Comment by outofcoffee** [comment]
Yes, and sorry for the trouble. Given the UX is not great for this feature, I wonder if it might be worth spending some time on the static load approach discussed above. In that model, I envisage that the state will be accessible to all scripts, since they will be initialised at the same point and have the same bindings. Happy to discuss further.

**Comment by outofcoffee** [comment]
Added documentation for this: https://docs.imposter.sh/groovy_tips/
