### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by arunamat** [outofcoffee/imposter#9]
Hi, Can you guide me on how to include CORS headers in API responses? Thank you.

**Comment by nexsja** [comment]
@arunamat They have to be defined in Swagger (OpenAPI) definitions, Imposter doesn't force any headers, yet. When #11 is merged then it will be possible to force certain response headers.

**Comment by outofcoffee** [comment]
Yes, defining them in the Swagger document should work. #11 is merged now.
